/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IFa6SolidList: typeof import('~icons/fa6-solid/list')['default']
    IFa6SolidMoon: typeof import('~icons/fa6-solid/moon')['default']
    IFa6SolidSun: typeof import('~icons/fa6-solid/sun')['default']
    IFa6SolidTrash: typeof import('~icons/fa6-solid/trash')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NInput: typeof import('naive-ui')['NInput']
    NSelect: typeof import('naive-ui')['NSelect']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
