name: E2E Tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:

    # Checkout the repository code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Install PNPM and Setup Node.js
    - name: Setup Environment
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'pnpm'
        cache-dependency-path: pnpm-lock.yaml

    # Install dependencies and build
    - name: Install and Build
      run: |
        pnpm install
        pnpm run build

    # Cache Cypress binary
    - name: Cache Cypress Binary
      uses: actions/cache@v4
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-cypress-

    # Install Cypress binary
    - name: Install Cypress
      run: pnpm cypress install

    # Start the server
    - name: Start Server
      run: pnpm start &
      env:
        NODE_ENV: devel

    # Wait for the server to be ready
    - name: Wait for Server to Start
      run: npx wait-on http://localhost:3000

    # Run Cypress tests
    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_NODE_ENV: ci
