name: Base Nuxt Module CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name : Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'pnpm'
        cache-dependency-path: pnpm-lock.yaml

    - name: Install dependencies
      run: pnpm i

    - name: Build module
      run: pnpm run build

    - name: Test module with Cypress
      uses: cypress-io/github-action@v6
      with:
        build: pnpm module:start
