name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name : Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'pnpm'
        cache-dependency-path: pnpm-lock.yaml

    - name: Install dependencies
      run: pnpm i

    - name: Build layer
      run: pnpm run build

    - name: Cache Cypress
      uses: actions/cache@v3
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-cypress-

    - name: Install Cypress
      run: pnpm cypress install

    - name: Start Server
      run: pnpm module:start &
      env:
        NODE_ENV: development

    - name: Wait for Server to be Ready
      run: npx wait-on http://localhost:3000

    - name: Test layer with Cypress
      uses: cypress-io/github-action@v6
      with:
        start: false
